# Generated by Django 4.2.5 on 2025-08-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[], max_length=3)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dato de Sensor',
                'verbose_name_plural': 'Datos de Sensores',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='DataBaseEt0',
        ),
        migrations.DeleteModel(
            name='DataBaseEt1',
        ),
        migrations.DeleteModel(
            name='DataBaseHumidity',
        ),
        migrations.DeleteModel(
            name='DataBaseHumidityMax',
        ),
        migrations.DeleteModel(
            name='DataBaseHumidityMin',
        ),
        migrations.DeleteModel(
            name='DataBasePrecipitation',
        ),
        migrations.DeleteModel(
            name='DataBasePressure',
        ),
        migrations.DeleteModel(
            name='DataBaseRadiation',
        ),
        migrations.DeleteModel(
            name='DataBaseTemperature',
        ),
        migrations.DeleteModel(
            name='DataBaseTemperatureMax',
        ),
        migrations.DeleteModel(
            name='DataBaseTemperatureMin',
        ),
        migrations.DeleteModel(
            name='DataBaseWindVelocity',
        ),
    ]
