# Generated by Django 4.2.5 on 2025-08-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0002_sensordata_delete_databaseet0_delete_databaseet1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('PRE', 'Radiación'), ('RAD', 'Radiación'), ('HUM', 'Humedad'), ('TEM', 'Temperatura'), ('TEM2', 'Temperatura')], max_length=10),
        ),
    ]
