# Generated by Django 4.2.5 on 2025-08-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0003_alter_sensordata_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('PRE', 'Radiación'), ('RAD', 'Radiación'), ('HUM', 'Humedad'), ('TEM', 'Temperatura'), ('TEM3', 'Temperatura 2'), ('TEM3', 'Temperatura 2')], max_length=10),
        ),
    ]
