# Generated by Django 4.2.5 on 2025-08-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0004_alter_sensordata_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('PRE', 'Radiación'), ('RAD', 'Radiación'), ('TEM3', 'Temperatura 2'), ('TEM3', 'Temperatura 3')], max_length=10),
        ),
    ]
