# Generated by Django 4.2.5 on 2025-08-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0005_alter_sensordata_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('TEM2', 'Temperatura_2'), ('TEM3', 'Temperatura_3'), ('PRE', 'Radiación'), ('RAD', 'Radiación'), ('HUM', 'Humedad'), ('TEM', 'Temperatura')], max_length=10),
        ),
    ]
