# Generated by Django 4.2.5 on 2025-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0006_alter_sensordata_sensor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('PRE', 'Presión'), ('RAD', 'Radiación'), ('HUM', 'Humedad'), ('TEM', 'Temperatura')], max_length=10),
        ),
    ]
