# Generated by Django 4.2.5 on 2025-08-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0007_alerta_alter_sensordata_sensor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='sensor_id',
        ),
    ]
