# Generated by Django 4.2.5 on 2025-08-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0008_remove_alerta_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('PRE', 'Presión'), ('RAD', 'Radiación'), ('HUM', 'Humedad'), ('TEM', 'Temperatura'), ('Wind', 'Viento')], max_length=10),
        ),
    ]
